---
title: "A Firm-Level Perspective on Industrial Resilience in a Crisis"
date: 2022-06-01
categories: [Blog]
description: "The significance of industrial capabilities for robustness to the pandemic crisis."
---

History has shown that health and economic shocks are recurrent events; robustness to one such shock must be followed by preparedness for the next one. "The new normal" is a phrase that has been used throughout the COVID-19 pandemic to signal the need for fundamental change to follow the crisis. Resilience at both the government and sector levels can create conditions for countries to better withstand and recover from shocks. Research based on World Bank data shows that manufacturing firms in countries with stronger industrial capabilities — proxied by higher Competitive Industrial Performance (CIP) scores — were more likely to remain in operation and experienced higher growth rates (or lower losses) in employment.

This piece is part of the IAP IDR2022 series, based on UNIDO's flagship [Industrial Development Report (IDR) 2022](https://www.unido.org/idr2022).

[[{{< fa newspaper >}} Read the full article on UNIDO ↗](https://iap.unido.org/articles/firm-level-perspective-industrial-resilience-crisis)]{.news-links}
